- name: "Copy service script file to remote server"
  ansible.builtin.template:
    src: simple-deploy.sh.j2
    dest: "{{ remote_app_path }}/service.sh"
    owner: "{{ remote_server_user }}"
    group: "{{ remote_server_group }}"
    mode: 0755

- name: "Shutdown the old application - {{ app_port }}"
  ansible.builtin.command: "{{ remote_app_path }}/service.sh shutdown {{ app_port }}"
  register: result
  become: false

- ansible.builtin.debug:
    msg: "{{ result.stdout_lines }}"

- name: "Run service script - {{ app_port }}"
  ansible.builtin.command: "{{ remote_app_path }}/service.sh run {{ app_port }}"
  register: result
  become: false

- ansible.builtin.debug:
    msg: "{{ result.stdout_lines }}"
