pipeline {
  agent {
    label 'ansible-agent'
  }

  // Disallow concurrent executions of the Pipeline.
  options { disableConcurrentBuilds() }

  environment {
    APP_NAME = "cicd-demo"
    APP_PORT = 8081
    JAR_NAME = "${APP_NAME}.jar"
    SPRING_PROFILE = "prod"
    ANSIBLE_INVENTORY = "${HOME}/ansible/inventory"
    ANSIBLE_PLAYBOOK = "${WORKSPACE}/jenkins-ansible/playbook/deploy-app.yml"
  }

  stages {
    stage('Init') {
      steps {
        script {
          sh 'printenv'
        }
      }
    }

    stage('Test') {
      steps {
        sh './gradlew clean test'
      }
    }

    stage('Build') {
      steps {
        sh './gradlew clean build -x test'
      }
    }

    stage('Deploy') {
      steps {
        lock(resource: 'deployment') {
          // 1. transfer application build artifact
          sshPublisher(
            publishers: [
              sshPublisherDesc(
                configName: 'remote-server',
                transfers: [
                  sshTransfer(
                    cleanRemote: false,
                    excludes: '',
                    execTimeout: 120000,
                    flatten: false,
                    makeEmptyDirs: false,
                    noDefaultExcludes: false,
                    patternSeparator: '[, ]+',
                    remoteDirectory: 'deploy',
                    remoteDirectorySDF: false,
                    removePrefix: 'build/libs',
                    sourceFiles: "build/libs/${JAR_NAME}",
                  )
                ],
                usePromotionTimestamp: false,
                useWorkspaceInPromotion: false,
                verbose: true
              )
            ]
          )
          // 2. deploy the application using Ansible Playbook
          ansiblePlaybook(
            installation: 'ansible-agent',
            disableHostKeyChecking: true, // not recommended (only for demo environment)
            inventory: "${ANSIBLE_INVENTORY}",
            playbook: "${ANSIBLE_PLAYBOOK}",
            extraVars: [
              app_name: "${APP_NAME}",
              spring_profile: "${SPRING_PROFILE}",
              app_port: "${APP_PORT}"
            ]
          )
        }
      }
    }
  }
}