pipeline {
  agent {
    label 'ansible-agent'
  }

  // Disallow concurrent executions of the Pipeline.
  options { disableConcurrentBuilds() }

  stages {
    stage('Init') {
      steps {
        script {
          sh 'printenv'
        }
      }
    }

    stage('Test') {
      steps {
        sh './gradlew clean test'
      }
    }

    stage('Build') {
      steps {
        sh './gradlew clean build -x test'
      }
    }
  }
}