pipeline {
  agent {
    label 'ansible-agent'
  }

  // Disallow concurrent executions of the Pipeline.
  options { disableConcurrentBuilds() }

  stages {
    stage('Init') {
      steps {
        script {
          ANSIBLE_INVENTORY = "${HOME}/ansible/inventory"
          ANSIBLE_PLAYBOOK = "${WORKSPACE}/jenkins-ansible/playbook/test.yaml"
          sh 'printenv'
        }
      }
    }

    stage('Test') {
      steps {
        sh './gradlew clean test'
      }
    }

    stage('Build') {
      steps {
        sh './gradlew clean build -x test'
      }
    }

    stage('Deploy') {
      steps {
        lock(resource: 'deployment') {
          ansiblePlaybook(
            installation: 'ansible-agent',
            inventory: "${ANSIBLE_INVENTORY}",
            playbook: "${ANSIBLE_PLAYBOOK}",
            extraVars: [
              hello: "world",
              beanie: "joy"
            ]
          )
        }
      }
    }
  }
}