---
- name: "Deploy Demo App"
  hosts: appservers
  become: true  # root privilege
  vars_files:
    - group_vars/all.yml
  tags:
    - deploy
  roles:
    - package
    - nginx
    - setup
    - run-app
