---
- name: "Deploy Demo App"
  hosts: appservers
  become: true  # root privilege
  vars_files:
    - group_vars/all.yml
  roles:
    - role: package
      tags:
        - deploy
    - role: nginx
      tags:
        - deploy
    - role: setup
      tags:
        - deploy
    - role: run-app
