- name: "[Blue Green] Check GREEN applications runnable"
  ansible.builtin.command: "{{ remote_app_path }}/service.sh check GREEN"
  register: result
  become: false

- ansible.builtin.debug:
    msg: "{{ result.stdout_lines }}"

- name: "[Blue Green] Run new version on GREEN group"
  ansible.builtin.command: "{{ remote_app_path }}/service.sh run GREEN"
  register: result
  become: false

- ansible.builtin.debug:
    msg: "{{ result.stdout_lines }}"

- name: "[Blue Green] Switch proxy upstream between BLUE and GREEN"
  ansible.builtin.command: "{{ remote_app_path }}/service.sh switch_proxy"
  register: result
  become: false

- ansible.builtin.debug:
    msg: "{{ result.stdout_lines }}"

- name: "[Blue Green] Shutdown old applications in GREEN group"
  ansible.builtin.command: "{{ remote_app_path }}/service.sh shutdown GREEN"
  register: result
  become: false

- ansible.builtin.debug:
    msg: "{{ result.stdout_lines }}"
