pipeline {
  agent any

  environment {
    PORT = '8081'
    APP_NAME = 'cicd-demo'
    SCRIPT_FILE = 'deploy.sh'
    JAR_NAME = '${APP_NAME}.jar'
    SPRING_PROFILE = 'prod'
    REMOTE_WORK_DIR = '/home/app/deploy'
  }

  // Disallow concurrent executions of the Pipeline.
  options { disableConcurrentBuilds() }

  stages {
    stage('Init') {
      steps {
        script {
          sh 'printenv'
        }
      }
    }

    stage('Test') {
      steps {
        sh './gradlew clean test'
      }
    }

    stage('Build') {
      steps {
        sh './gradlew clean build -x test'
      }
    }

    stage('Deploy') {
      steps {
        lock(resource: 'deployment') {
          sshPublisher(
            publishers: [
              sshPublisherDesc(
                configName: 'remote-server',
                transfers: [
                  // 1. transferring bash script file to manage in project's repository
                  sshTransfer(
                    execTimeout: 120000,
                    patternSeparator: '[, ]+',
                    remoteDirectory: 'deploy',
                    removePrefix: '/jenkins-only',
                    sourceFiles: "/jenkins-only/${SCRIPT_FILE}",
                    execCommand: "chmod 500 ${SCRIPT_FILE}",
                  ),
                  // 2. deploying application file
                  sshTransfer(
                    cleanRemote: false,
                    excludes: '',
                    execTimeout: 120000,
                    flatten: false,
                    makeEmptyDirs: false,
                    noDefaultExcludes: false,
                    patternSeparator: '[, ]+',
                    remoteDirectory: 'deploy',
                    remoteDirectorySDF: false,
                    removePrefix: '/build/libs',
                    sourceFiles: "/build/libs/${JAR_NAME}",
                    execCommand: """
                      cd ${REMOTE_WORK_DIR}
                      ./deploy.sh ${PORT} ${REMOTE_WORK_DIR} ${SPRING_PROFILE} ${JAR_NAME}
                    """,
                  )
                ],
                usePromotionTimestamp: false,
                useWorkspaceInPromotion: false,
                verbose: false
              )
            ]
          )
        }
      }
    }
  }
}